{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "En este laboratorio pondremos en práctica algunos de los conceptos que hemos aprendido en los últimos días.\n",
    "\n",
    "`NOTA: En este laboratorio deberías intentar escribir todas las funciones por ti mismo utilizando solo la sintaxis más básica de Python y sin funciones como len, count, sum, max, min, in, etc. Dale una oportunidad. 🧑🏻‍💻👩🏻‍💻`\n",
    "\n",
    "La celda después de cada ejercicio contiene algunas pruebas para verificar si tu función funciona como se espera."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mod.testing import *\n",
    "import unittest"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Escribe una función que devuelva el mayor de dos números"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def greater(a,b):\n",
    "    if a > b:\n",
    "        return a\n",
    "    return b\n",
    "#your code here#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.080s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# Para testear tu función\n",
    "test_greater(greater)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Ahora escribe una función que devuelva el elemento más"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "#tu codigo aquí\n",
    "def greatest(lst):\n",
    "    aux = 0\n",
    "    for element in lst:\n",
    "        if element > aux:\n",
    "            aux = element\n",
    "    return aux"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.081s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# Para testear tu función\n",
    "test_greatest(greatest)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Escribe una función que sume todos los elementos de una lista"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sum_all(lst):\n",
    "    result = 0\n",
    "    for element in lst:\n",
    "        result += element\n",
    "    return result\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.082s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# Para testear tu función\n",
    "test_sum(sum_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Escribe otra función que multiplique todos los elementos de una lista"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mult_all(lst):\n",
    "    result = 1\n",
    "    for element in lst:\n",
    "        result *= element\n",
    "    return result\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.078s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# Para testear tu función\n",
    "test_mult(mult_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Ahora combina esas dos ideas y escribe una función que reciba una lista y ya sea \"+\" o \"*\", y produzca el resultado acorde"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "def oper_all(arr, oper = \"*\"):\n",
    "    if oper == '*':\n",
    "        return mult_all(arr)\n",
    "    else:\n",
    "        return sum_all(arr)\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.082s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# Para testear tu función\n",
    "test_operations(oper_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Escribe una función que devuelva el factorial de un número."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "def factorial(n):\n",
    "    if n == 1:\n",
    "        return 1\n",
    "    return n * factorial(n-1)\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Fórmula factorial\n",
    "# n! = n * (n - 1) *...*1\n",
    "\n",
    "# Este código define una función llamada \"factorial\" que toma una entrada \"n\". La función utiliza un bucle for para iterar a través del rango de números\n",
    "# desde 1 hasta n+1. Para cada número en ese rango, multiplica el valor actual de x por el número en el rango. Al final del bucle,\n",
    "# la función devuelve el valor final de x, que será el factorial del número de entrada \"n\".\n",
    "\n",
    "# El factorial de un entero positivo n es el producto de todos los enteros positivos menores o iguales a n.\n",
    "# Por ejemplo, el factorial de 6 (escrito \"6!\") es 6 * 5 * 4 * 3 * 2 * 1 = 720.\n",
    "\n",
    "# Así que esta función toma una entrada de cualquier entero positivo y devuelve el factorial de ese número."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.063s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_factorial(factorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Escribe una función que tome una lista y devuelva una lista de los valores únicos.\n",
    "\n",
    "`NOTE: No podemos usar set. 🤔`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "incomplete input (3978216279.py, line 2)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[17], line 2\u001b[0;36m\u001b[0m\n\u001b[0;31m    #tu codigo aquí\u001b[0m\n\u001b[0m                   ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m incomplete input\n"
     ]
    }
   ],
   "source": [
    "def unique(lst_un):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función \n",
    "test_unique(unique)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Escribe una función que devuelva la moda de una lista, es decir: el elemento que aparece más veces.\n",
    "\n",
    "`NOTE: No se debe usar count... 🧐`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def mode_counter(arr):\n",
    "    dict_={}\n",
    "    veces=0\n",
    "    for i in arr:\n",
    "        if i in dict_:\n",
    "            dict_[i]+=1\n",
    "        else:\n",
    "            dict_[i]=1\n",
    "    for i in dict_:\n",
    "        if dict_[i]>veces:\n",
    "            veces=dict_[i]\n",
    "            moda=i\n",
    "        else:\n",
    "            veces\n",
    "            moda\n",
    "    return moda"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.320s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# Para testear tu función \n",
    "test_mode(mode_counter)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Escribe una función que calcule la desviación estándar de una lista.\n",
    "`NOTE: no utilices librerías ni ninguna función ya construida. 😉`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [],
   "source": [
    "def st_dev(list_sd):\n",
    "    promedio = 0\n",
    "    for i in list_sd:\n",
    "        promedio += i\n",
    "    promedio = promedio / len(list_sd)\n",
    "\n",
    "    varianza = 0\n",
    "\n",
    "    for i in list_sd:\n",
    "        varianza += (i - promedio)**2\n",
    "    \n",
    "    varianza = varianza / len(list_sd)\n",
    "    desviacion = varianza**0.5\n",
    "    return desviacion\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FF..FF..F.FFF...FF.....FFF.FF.FF.FF.F..FF.FFFFFFF...FFF.F...FFFFFF.F..FFFFFFFFF.FF...F.FFFF...FFFF..\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 529.635823243819 != 544.1490808796999 within 5 delta (14.513257635880905 difference) : Should be 544.1490808796999\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 590.2420067747404 != 597.9579160490493 within 5 delta (7.715909274308956 difference) : Should be 597.9579160490493\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 518.9477925847372 != 526.5240735237088 within 5 delta (7.5762809389716494 difference) : Should be 526.5240735237088\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 523.149420451064 != 528.5708027666823 within 5 delta (5.4213823156183025 difference) : Should be 528.5708027666823\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 555.6564218756025 != 566.6605875993685 within 5 delta (11.004165723765936 difference) : Should be 566.6605875993685\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 666.9587731179887 != 672.3159577578176 within 5 delta (5.357184639828915 difference) : Should be 672.3159577578176\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 571.4890336266791 != 591.5473494714237 within 5 delta (20.058315844744584 difference) : Should be 591.5473494714237\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 550.9493874213855 != 565.2621445889183 within 5 delta (14.312757167532823 difference) : Should be 565.2621445889183\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 622.4480299773104 != 629.1773934387909 within 5 delta (6.729363461480489 difference) : Should be 629.1773934387909\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 536.9852148687655 != 543.0530370139744 within 5 delta (6.067822145208879 difference) : Should be 543.0530370139744\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 667.990482955079 != 686.2949811630496 within 5 delta (18.304498207970596 difference) : Should be 686.2949811630496\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 526.3676069060481 != 537.221689187372 within 5 delta (10.85408228132394 difference) : Should be 537.221689187372\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 607.819738096094 != 619.3982973113913 within 5 delta (11.578559215297219 difference) : Should be 619.3982973113913\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 456.1230206863056 != 480.79587953494126 within 5 delta (24.672858848635656 difference) : Should be 480.79587953494126\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 534.43082676222 != 551.9577844666504 within 5 delta (17.5269577044304 difference) : Should be 551.9577844666504\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 478.95713126933396 != 494.6647981209094 within 5 delta (15.707666851575425 difference) : Should be 494.6647981209094\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 621.5551185792768 != 627.3914449187466 within 5 delta (5.836326339469792 difference) : Should be 627.3914449187466\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 526.6993331114062 != 550.1195118087771 within 5 delta (23.420178697370943 difference) : Should be 550.1195118087771\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 530.0515335869594 != 540.1486605542733 within 5 delta (10.097126967313898 difference) : Should be 540.1486605542733\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 620.367304182583 != 627.3773267348845 within 5 delta (7.010022552301507 difference) : Should be 627.3773267348845\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 553.6457825972717 != 560.5236336698382 within 5 delta (6.8778510725665 difference) : Should be 560.5236336698382\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 489.4121383976265 != 497.243229855467 within 5 delta (7.8310914578405 difference) : Should be 497.243229855467\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 544.3386899486385 != 562.1905815646505 within 5 delta (17.85189161601204 difference) : Should be 562.1905815646505\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 607.1058013901965 != 618.246286603867 within 5 delta (11.140485213670559 difference) : Should be 618.246286603867\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 676.0746284440842 != 687.2501727900838 within 5 delta (11.175544345999583 difference) : Should be 687.2501727900838\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 523.986836683233 != 531.8667801583467 within 5 delta (7.879943475113691 difference) : Should be 531.8667801583467\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 596.5526861708427 != 604.7813877981258 within 5 delta (8.228701627283158 difference) : Should be 604.7813877981258\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 539.5080479820751 != 551.6333382972322 within 5 delta (12.12529031515703 difference) : Should be 551.6333382972322\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 570.6561847341974 != 579.5040950779564 within 5 delta (8.847910343759054 difference) : Should be 579.5040950779564\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 534.0024698024364 != 554.1605521709549 within 5 delta (20.158082368518535 difference) : Should be 554.1605521709549\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 667.9039156439677 != 681.1310198147241 within 5 delta (13.227104170756434 difference) : Should be 681.1310198147241\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 549.1263372074554 != 554.1875164301371 within 5 delta (5.061179222681631 difference) : Should be 554.1875164301371\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 615.4062607615388 != 629.237341875915 within 5 delta (13.831081114376275 difference) : Should be 629.237341875915\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 467.3349348786421 != 480.8836807161218 within 5 delta (13.548745837479657 difference) : Should be 480.8836807161218\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 531.427929375854 != 540.2124572098751 within 5 delta (8.784527834021105 difference) : Should be 540.2124572098751\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 628.9273725075071 != 646.1614503226272 within 5 delta (17.23407781512003 difference) : Should be 646.1614503226272\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 582.0459781333061 != 591.0704849523602 within 5 delta (9.024506819054068 difference) : Should be 591.0704849523602\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 578.1404046596294 != 593.1595396465307 within 5 delta (15.019134986901236 difference) : Should be 593.1595396465307\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 456.7576502239041 != 463.62657175707227 within 5 delta (6.868921533168191 difference) : Should be 463.62657175707227\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 546.7897473232081 != 562.6420082181606 within 5 delta (15.852260894952565 difference) : Should be 562.6420082181606\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 499.7278634416936 != 516.116718065465 within 5 delta (16.38885462377135 difference) : Should be 516.116718065465\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 481.11878124171795 != 491.9317893524407 within 5 delta (10.813008110722762 difference) : Should be 491.9317893524407\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 582.4231252532766 != 587.6003215150682 within 5 delta (5.177196261791664 difference) : Should be 587.6003215150682\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 604.1652148256245 != 617.743656621776 within 5 delta (13.578441796151537 difference) : Should be 617.743656621776\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 509.9563314637832 != 523.204156590603 within 5 delta (13.247825126819805 difference) : Should be 523.204156590603\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 595.1859181893371 != 602.4005563689237 within 5 delta (7.214638179586586 difference) : Should be 602.4005563689237\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 633.3639327446544 != 645.9070104541722 within 5 delta (12.543077709517775 difference) : Should be 645.9070104541722\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 564.6931394648185 != 570.0970246911342 within 5 delta (5.403885226315651 difference) : Should be 570.0970246911342\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 571.2014804663781 != 576.7743098036459 within 5 delta (5.572829337267763 difference) : Should be 576.7743098036459\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 632.2028325526574 != 647.0802288053796 within 5 delta (14.877396252722292 difference) : Should be 647.0802288053796\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 586.0206545954304 != 594.8334897855113 within 5 delta (8.812835190080932 difference) : Should be 594.8334897855113\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 569.7269982649452 != 576.0225153275271 within 5 delta (6.295517062581894 difference) : Should be 576.0225153275271\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 551.2250056036293 != 564.8375493386193 within 5 delta (13.612543734990027 difference) : Should be 564.8375493386193\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 563.5915868901145 != 573.5674336860677 within 5 delta (9.975846795953203 difference) : Should be 573.5674336860677\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 504.63020689836407 != 511.9974609312042 within 5 delta (7.367254032840151 difference) : Should be 511.9974609312042\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 639.0815061379911 != 646.4699770984269 within 5 delta (7.388470960435711 difference) : Should be 646.4699770984269\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 566.5632892604816 != 573.6016124071633 within 5 delta (7.038323146681705 difference) : Should be 573.6016124071633\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 556.7013462251452 != 562.5925298205879 within 5 delta (5.891183595442612 difference) : Should be 562.5925298205879\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 633.87048094741 != 639.1309070866802 within 5 delta (5.26042613927018 difference) : Should be 639.1309070866802\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_stdev.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/ubuntu/jupyter/lab-functions-es/mod/testing.py\", line 142, in runTest\n",
      "    self.assertAlmostEqual(fn(self.input), self.output, delta=5, msg=f\"Should be {self.output}\")\n",
      "AssertionError: 596.7159107139456 != 610.7582063141572 within 5 delta (14.04229560021156 difference) : Should be 610.7582063141572\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.089s\n",
      "\n",
      "FAILED (failures=60)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "280514.1052631579\n",
      "348385.6265614727\n",
      "343010.358367347\n",
      "325735.54678204446\n",
      "269306.8114285714\n",
      "273685.3161182841\n",
      "316971.3009323546\n",
      "309826.27405917825\n",
      "308754.0591715976\n",
      "314202.0895792243\n",
      "444834.00503905275\n",
      "326599.71555555554\n",
      "303545.2275\n",
      "364474.62489149283\n",
      "334473.8110651975\n",
      "305737.3869387756\n",
      "387441.55002263474\n",
      "288353.1209876543\n",
      "314720.63269054185\n",
      "353193.6497620463\n",
      "283286.5891555555\n",
      "319126.5308159721\n",
      "300840.18605703936\n",
      "446211.2853185596\n",
      "277062.85759999993\n",
      "369444.8340192043\n",
      "344921.6499\n",
      "208048.21\n",
      "285616.30859375\n",
      "348859.070415879\n",
      "229399.93359375\n",
      "386330.7654320989\n",
      "269845.1818442976\n",
      "277412.1875\n",
      "280954.6282578876\n",
      "372870.4313016528\n",
      "384855.5920987655\n",
      "297301.77634297527\n",
      "265579.3958613276\n",
      "306523.65258774546\n",
      "239524.2412109375\n",
      "357190.5175490779\n",
      "296304.609375\n",
      "368577.45408163266\n",
      "457076.9032258064\n",
      "274562.2050173011\n",
      "355875.10737764795\n",
      "291068.9338374291\n",
      "325648.48117539036\n",
      "316226.370675202\n",
      "346481.87249864795\n",
      "346839.1322222221\n",
      "285158.637755102\n",
      "446095.6405325443\n",
      "301539.734214876\n",
      "352433.8975426905\n",
      "378724.86578449904\n",
      "310723.4522714981\n",
      "355100.5027072053\n",
      "329909.0819555556\n",
      "218401.9413580247\n",
      "282415.64412070764\n",
      "395549.63988919667\n",
      "338777.52066115703\n",
      "334246.3275\n",
      "208627.5510380623\n",
      "337484.5185657595\n",
      "298979.02777777775\n",
      "261135.5925925926\n",
      "249027.38049586772\n",
      "249727.9375\n",
      "231475.28166351604\n",
      "339216.69682979386\n",
      "365015.60680529306\n",
      "260055.45999999996\n",
      "354246.2772108843\n",
      "401149.8713017752\n",
      "318878.3417586329\n",
      "326271.1312869822\n",
      "333348.33516988065\n",
      "399680.4214876033\n",
      "343420.2076124567\n",
      "274714.085255404\n",
      "344368.012641777\n",
      "404905.4153911563\n",
      "324588.85255198483\n",
      "309177.52776342985\n",
      "303849.00680272107\n",
      "317635.47681331745\n",
      "254651.6457142857\n",
      "408425.1714876033\n",
      "316993.5377999095\n",
      "314082.06726354454\n",
      "317000.13960000005\n",
      "320993.9607376562\n",
      "309916.38888888905\n",
      "401791.7866165009\n",
      "356069.87809917354\n",
      "305576.38646193774\n",
      "282329.72177273274\n"
     ]
    }
   ],
   "source": [
    "# Para testear tu función\n",
    "test_stdev(st_dev)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Escribe una función para verificar si una cadena es un pangrama, es decir: si contiene todas las letras del alfabeto al menos una vez. Ten en cuenta que las cadenas pueden contener caracteres que no son letras."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def pangram(string):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función\n",
    "test_pangram(pangram)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 11. Escribe una función que reciba una cadena de palabras separadas por comas y devuelva una cadena de palabras separadas por comas ordenadas alfabéticamente.\n",
    "\n",
    "`NOTA: Puedes usar sorted pero no split y definitivamente no join! 🤪`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "def sort_alpha(string):\n",
    "    pattern=r'(\\w+),'\n",
    "    orden=sorted(re.findall(pattern, string))\n",
    "    return orden"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['idrymbl', 'pmhhe', 'unfkcebbb', 'xxdpady'] != 'idrymbl,myeipz,pmhhe,unfkcebbb,xxdpady' : Should be idrymbl,myeipz,pmhhe,unfkcebbb,xxdpady\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['eiji', 'fkafhqy', 'flccmabxo', 'gqxucec[228 chars]anz'] != 'eiji,fkafhqy,flccmabxo,gqxucectx,guvuyi,[163 chars]janz' : Should be eiji,fkafhqy,flccmabxo,gqxucectx,guvuyi,gwyyd,iasmo,ismmidlmhk,jfspctrhp,jiaij,jpwxu,jxzztqthil,kgxwq,lgolrbibwg,lutujblj,qifuwapev,scaeiplslm,taqrppwxfo,tkbyfg,tlybx,umjnulshb,unkyaoky,ynxvoc,yvxjblp,zijanz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['ahuybcsqus', 'akgm', 'brpkrkfzj', 'elrf[151 chars]iaf'] != 'ahuybcsqus,akgm,brpkrkfzj,elrfkwb,jloz,j[103 chars]giaf' : Should be ahuybcsqus,akgm,brpkrkfzj,elrfkwb,jloz,jzkbh,lvkcvgir,miomxgjrr,njzmczqdn,nusamfeznr,orqqd,scks,sluohm,ughortip,uzdlmby,vkgsyv,wztxcgzpu,wzzy,xgiaf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['anedkrvws', 'bfug', 'cnstppfi', 'deaifp[103 chars]zlw'] != 'anedkrvws,bfug,cnstppfi,deaifppbwd,drhz,[72 chars]zzlw' : Should be anedkrvws,bfug,cnstppfi,deaifppbwd,drhz,jiraiq,mxswej,ooywmum,qhbjpmxai,qiiab,qsutpsemg,ukujwud,uodsyfktj,whbet,zzlw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['birxslw', 'blbssgycik', 'dlydj', 'ewanz[132 chars]gvp'] != 'birxslw,blbssgycik,dlydj,ewanzl,eycbwpao[93 chars]ugvp' : Should be birxslw,blbssgycik,dlydj,ewanzl,eycbwpao,gdgsbjlv,gmszzv,hiqwewicmd,hqypxjkctf,llqyogw,nega,orgmuozx,plxbkdgqra,pxjlynm,qtzywoi,xsfbcugvp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bsmbemj', 'pwbhs', 'qwpjqupfb'] != 'bsmbemj,ihaatcwa,pwbhs,qwpjqupfb' : Should be bsmbemj,ihaatcwa,pwbhs,qwpjqupfb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bhifolv', 'jmzxgbvm', 'jurca', 'nmgub',[71 chars]xgm'] != 'bhifolv,jmzxgbvm,jurca,nmgub,okfi,pthxsa[45 chars]yxgm' : Should be bhifolv,jmzxgbvm,jurca,nmgub,okfi,pthxsaukpv,rdcpubsp,tznftaqwh,vjtnpn,vwbmokk,xwfun,yxgm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['cnzh', 'crgc', 'cuae', 'hnneufqro', 'kc[106 chars]lxe'] != 'cnzh,crgc,cuae,hnneufqro,kctpbczkou,miyv[72 chars]wlxe' : Should be cnzh,crgc,cuae,hnneufqro,kctpbczkou,miyvjy,mwsfuxu,oscleigp,sijigr,suchpdl,tesjijm,vfkikt,wpvsfahwjn,xqpssk,yvufwlxe\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['atprgps', 'sjtljwbfu', 'uezd', 'ziauainsts'] != 'atprgps,fhiraane,sjtljwbfu,uezd,ziauainsts' : Should be atprgps,fhiraane,sjtljwbfu,uezd,ziauainsts\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['apyh', 'ewvponh', 'gisctkr', 'lqiebmb',[107 chars]ihh'] != 'apyh,ewvponh,gisctkr,lqiebmb,ngwik,pktge[70 chars]cihh' : Should be apyh,ewvponh,gisctkr,lqiebmb,ngwik,pktge,pldu,rjkcsnzij,rpqpybbbrb,ryeqf,twtwfv,ujpbl,wviqr,ymqijfes,zpfhj,zwicihh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['aqxcp', 'dvror', 'jrpjlfbdr', 'ozgtckzra', 'tymlcwshp', 'vawjqbfld'] != 'aqxcp,dvror,hqwdqrw,jrpjlfbdr,ozgtckzra,tymlcwshp,vawjqbfld' : Should be aqxcp,dvror,hqwdqrw,jrpjlfbdr,ozgtckzra,tymlcwshp,vawjqbfld\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['czeub', 'elzwq', 'evppcr', 'frwkd', 'fx[103 chars]ccu'] != 'czeub,djlgkk,elzwq,evppcr,frwkd,fxcy,fyc[69 chars]accu' : Should be czeub,djlgkk,elzwq,evppcr,frwkd,fxcy,fycefjsxu,juafbkhc,mhjgo,nlrvlptdk,pzmmxuzjlr,rgar,xxbbe,xzbcooabp,zsqpgaccu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bdsvkvl', 'cuohthrjwu', 'ditlkpdnrr', '[176 chars]jiw'] != 'bdsvkvl,cuohthrjwu,ditlkpdnrr,epweksqp,f[126 chars]ijiw' : Should be bdsvkvl,cuohthrjwu,ditlkpdnrr,epweksqp,fdtfwlicf,hvtfgx,iifljnrg,lhbe,mwnad,nsmwl,ophoog,qhodumspz,rtzzk,slgeekypq,ueduveognd,umfyjpr,voxxu,vslkw,wbyxg,xtdudupt,ztmtkijiw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bnihitem', 'czcx', 'ejld', 'eoyk', 'fky[102 chars]jzd'] != 'bnihitem,czcx,ejld,eoyk,fkybn,fnyenm,glk[65 chars]wjzd' : Should be bnihitem,czcx,ejld,eoyk,fkybn,fnyenm,glkas,krwoa,mhamutkvu,nmqu,odhm,okeqz,svavii,svdwomdyi,ufgd,ysjoi,zpwjzd\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['aphgueo', 'beiqwe', 'cmjqv', 'eitow', '[146 chars]yfv'] != 'aphgueo,beiqwe,cmjqv,eitow,izrnbrzvv,kux[107 chars]jyfv' : Should be aphgueo,beiqwe,cmjqv,eitow,izrnbrzvv,kuxdogptu,ndgtkiybng,ozfoxsyot,pgoe,puxpncymsr,qalxiifpb,spmacadik,uxcouqarl,vitaahe,wcdfj,wowcxm,yddqkwqagz,yjyfv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['autrilt', 'awyztfpi', 'bofwlypnp', 'dxh[181 chars]pqt'] != 'arvzlvwvo,autrilt,awyztfpi,bofwlypnp,dxh[132 chars]kpqt' : Should be arvzlvwvo,autrilt,awyztfpi,bofwlypnp,dxhybggo,hsdyarrxth,imwdnup,inoagwz,kkrrefezc,kvnspv,mged,mrfszudsl,obhg,ohmvf,pgqgagude,qyxf,uzonxrgkmz,vypcuyxr,xdsp,xhnatopfpe,xrwbckpqt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['dhltzhszx', 'dnvygrek', 'fofjhsdbj', 'm[39 chars]vls'] != 'dhltzhszx,dnvygrek,fofjhsdbj,mkrp,odebut[26 chars]zvls' : Should be dhltzhszx,dnvygrek,fofjhsdbj,mkrp,odebutkek,rgypn,tcla,ylswmtqugo,zvls\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bdrjcp', 'csqjgrnzxq', 'lwwcoy', 'noigjtcz', 'nqurrofmu', 'pbgq', 'pnixdqn'] != 'bdrjcp,csqjgrnzxq,lwwcoy,noigjtcz,nqurrofmu,pbgq,pnixdqn,wzawzzrh' : Should be bdrjcp,csqjgrnzxq,lwwcoy,noigjtcz,nqurrofmu,pbgq,pnixdqn,wzawzzrh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['dpwxivwxa', 'kfcq', 'kubkvpzguj', 'qfkpqot', 'vhopfz'] != 'dpwxivwxa,kfcq,kubkvpzguj,qfkpqot,shpl,vhopfz' : Should be dpwxivwxa,kfcq,kubkvpzguj,qfkpqot,shpl,vhopfz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['aflpqvc', 'blwycs', 'ehdamslgz', 'felji[126 chars]jrh'] != 'aflpqvc,blwycs,ehdamslgz,feljivnyb,jdorn[91 chars]kjrh' : Should be aflpqvc,blwycs,ehdamslgz,feljivnyb,jdornwsyy,nxtky,qyym,rdqgplkuse,txzjruywg,uxrklfmrt,vlnc,wcxcnuyih,wmbskrvv,wzchpuild,xbarg,xutqkjrh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bltt', 'qacjz', 'rtgpyroln', 'wzdghq'] != 'bltt,qacjz,rtgpyroln,ufdofmkvjm,wzdghq' : Should be bltt,qacjz,rtgpyroln,ufdofmkvjm,wzdghq\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['aykvlevs', 'cibrchjiv', 'dprwu', 'iayelqjh', 'igxy', 'jeitrevw', 'yfysgyrsw'] != 'aykvlevs,cibrchjiv,dprwu,iayelqjh,igxy,jeitrevw,xdprvv,yfysgyrsw' : Should be aykvlevs,cibrchjiv,dprwu,iayelqjh,igxy,jeitrevw,xdprvv,yfysgyrsw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bfdze', 'cvvofr', 'iaerjqfv', 'jvoqiveth', 'rdlkxqydg', 'rgdksymc', 'ygwiwrx'] != 'bfdze,cvvofr,iaerjqfv,jvoqiveth,rdlkxqydg,rgdksymc,ulsrdhimed,ygwiwrx' : Should be bfdze,cvvofr,iaerjqfv,jvoqiveth,rdlkxqydg,rgdksymc,ulsrdhimed,ygwiwrx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['amib', 'emkpivl', 'exfjlv', 'fqnr', 'im[195 chars]hau'] != 'amib,emkpivl,exfjlv,fqnr,imeezmm,ixxc,jf[134 chars]fhau' : Should be amib,emkpivl,exfjlv,fqnr,imeezmm,ixxc,jfjrwvyfh,jwwxr,kcsqz,ktfxbokqg,kudxpvxi,lkpq,mulddet,nfcttx,nszpeflfr,oyxfrwpe,pchajoz,qcxosxq,qihcuxtac,rovbc,vyuntu,wwjfk,yutfxc,zifyfhau\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['ekjrg', 'hsodky', 'jvck', 'krgnzd', 'me[104 chars]lvw'] != 'ekjrg,gknaucd,hsodky,jvck,krgnzd,mejbbnw[71 chars]ylvw' : Should be ekjrg,gknaucd,hsodky,jvck,krgnzd,mejbbnwve,okowzynj,onwmarsmmw,pdyr,skslf,uouir,utguk,xqmdizhd,zcjwizima,zxtdneylvw\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['aicqub', 'ejohqvvgwx', 'etnwgpw', 'fjvf[83 chars]fyi'] != 'aicqub,bmlo,ejohqvvgwx,etnwgpw,fjvfoo,gj[50 chars]yfyi' : Should be aicqub,bmlo,ejohqvvgwx,etnwgpw,fjvfoo,gjui,howu,igdz,jprk,llkgok,mzvqzxe,pctax,xfknbjsyqk,yfyi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['brjdodx', 'cxcjtf', 'dajaxsqf', 'dehqux[220 chars]rjj'] != 'brjdodx,cxcjtf,dajaxsqf,dehquxfq,euufvsf[163 chars]orjj' : Should be brjdodx,cxcjtf,dajaxsqf,dehquxfq,euufvsfere,fkzuwcctw,haliqqhqwh,ixyzgkkvk,jbfyfub,jkbk,kjqopci,ktdhdslxbv,lqylfmtvcx,megjcia,mnxslqy,njoltzdtu,oileuh,ppuwkno,slpleeqtb,sqxsqkmusg,sxysd,uzgxe,wzpglirko,zorjj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bonhqekcre', 'djbueecj', 'piymreuxhc', 'plwwmqw', 'qumtau', 'soke'] != 'bonhqekcre,djbueecj,piymreuxhc,plwwmqw,qumtau,soke,tkttdx' : Should be bonhqekcre,djbueecj,piymreuxhc,plwwmqw,qumtau,soke,tkttdx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['cfiiegwue', 'cjqjhwrf', 'hwlrb', 'iydkqikoge', 'kwlgfgoh'] != 'bwihtjkyh,cfiiegwue,cjqjhwrf,hwlrb,iydkqikoge,kwlgfgoh' : Should be bwihtjkyh,cfiiegwue,cjqjhwrf,hwlrb,iydkqikoge,kwlgfgoh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['daembcmat', 'epdca', 'ezjadj', 'jephbe'[63 chars]lgh'] != 'daembcmat,epdca,ezjadj,ifcul,jephbe,lbkv[40 chars]plgh' : Should be daembcmat,epdca,ezjadj,ifcul,jephbe,lbkvoy,pixdzsdr,pqpazyqb,soicagffp,udtxtjk,vplgh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['auzs', 'bsgd', 'dpzefiy', 'drhc', 'iukt[75 chars]kdb'] != 'auzs,bsgd,dpzefiy,drhc,iuktrgi,jqbno,lsj[44 chars]kkdb' : Should be auzs,bsgd,dpzefiy,drhc,iuktrgi,jqbno,lsjxj,ncay,phhc,qwbpa,rubs,sfibfm,sxriiwixhn,vikkdb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['ahtjl', 'aifvkcniyg', 'ezevw', 'fcwlg',[167 chars]umj'] != 'ahtjl,aifvkcniyg,epncsxo,ezevw,fcwlg,fda[119 chars]yumj' : Should be ahtjl,aifvkcniyg,epncsxo,ezevw,fcwlg,fdasvwpbok,fmgzfv,gwnafmdy,iaqnv,ihobocdfb,mjmdngjswv,muoz,nbvzejsg,rgsaqusntb,sckgyibum,teoqxdt,vcshj,xfldvmax,xjjfvh,yycyumj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['hphhzclwyt', 'isbugwjm', 'jktu', 'jroqg[44 chars]fou'] != 'hphhzclwyt,isbugwjm,jktu,jroqg,ojjp,onsf[30 chars]ifou' : Should be hphhzclwyt,isbugwjm,jktu,jroqg,ojjp,onsfcyo,pnpsdekk,tvicehbhle,xsziomifou\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['cgtfrb', 'ckcqr', 'dehjelygt', 'gxggwhy[107 chars]ckg'] != 'cgtfrb,ckcqr,dehjelygt,gxggwhy,hhmjagwj,[73 chars]vckg' : Should be cgtfrb,ckcqr,dehjelygt,gxggwhy,hhmjagwj,lgwmqru,lzggzwc,mnjra,mzjjvnd,ngphcmqd,rnwbwhee,tmjebo,vpcbpinh,wvxn,xvjxvckg\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['abkulnd', 'auzkria', 'bqwmyujvv', 'cewj[176 chars]rrh'] != 'abkulnd,auzkria,bqwmyujvv,cewj,csjhulnip[125 chars]vrrh' : Should be abkulnd,auzkria,bqwmyujvv,cewj,csjhulnipt,cvppipbos,cxqw,efdapmtx,gamtxosze,jgmb,jnqa,qdzd,rdqnvp,rmwxrhn,rwcwna,tqbpjiw,upufzupcxh,vvpjwvfz,wmabrnu,wraqa,xjezl,zcycvrrh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['fhgvc', 'lwyhuvwul', 'mrdtrqc', 'todl', 'wptlzfkhah', 'xbvqo', 'zscgt'] != 'fhgvc,khcxeao,lwyhuvwul,mrdtrqc,todl,wptlzfkhah,xbvqo,zscgt' : Should be fhgvc,khcxeao,lwyhuvwul,mrdtrqc,todl,wptlzfkhah,xbvqo,zscgt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['awkrwmhe', 'bgysexuu', 'bity', 'bjmd', [121 chars]dly'] != 'awkrwmhe,bgysexuu,bity,bjmd,dgsmphehez,g[88 chars]ndly' : Should be awkrwmhe,bgysexuu,bity,bjmd,dgsmphehez,gopnnsoznr,ocaotvnuri,pmfghfgt,qrdvgkmnjw,rjdhje,slbco,ufoxnt,uzrksq,vuootmc,xzjtvlal,zvtndly\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['cyuktb', 'deewj', 'dglvgeqs', 'hqbd', '[71 chars]vzc'] != 'cyuktb,deewj,dglvgeqs,hqbd,hvwtwscipp,ic[44 chars]nvzc' : Should be cyuktb,deewj,dglvgeqs,hqbd,hvwtwscipp,icuyb,ipxzekyxl,kszsgyn,psrwbiwv,qfcw,uicd,urznvzc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['alnjghgrer', 'dyrhtiygn', 'egehuk', 'ht[123 chars]xwq'] != 'alnjghgrer,dyrhtiygn,egehuk,htcognutol,i[89 chars]nxwq' : Should be alnjghgrer,dyrhtiygn,egehuk,htcognutol,ierjb,ktnxcols,prmyt,qskptavfe,sqrwcy,svocoqud,urfllfjps,wmkiroi,xhjj,yqasamutv,yrefum,znbnxwq\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['jfhnygrn', 'kfwwnxke', 'kqmyiote', 'ltl[73 chars]jqz'] != 'jfhnygrn,kfwwnxke,kqmyiote,ltlflgandj,ly[49 chars]ojqz' : Should be jfhnygrn,kfwwnxke,kqmyiote,ltlflgandj,lyij,nicffyqqf,nsqtyd,ormgetqpt,qvpc,qxxhpwssns,vzrojqz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['clqgp', 'dmayqdzo', 'gdev', 'ixobb', 'k[95 chars]xjx'] != 'clqgp,dmayqdzo,gdev,ixobb,kisclqoqj,kqjv[64 chars]zxjx' : Should be clqgp,dmayqdzo,gdev,ixobb,kisclqoqj,kqjvwlgsdq,qriewrm,thvrsuapq,tkibij,ulel,uvqy,vgvgmysqgf,vnwl,wicqkmzxjx\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['aeysh', 'cedk', 'ctwipq', 'czzd', 'hsmg[93 chars]xue'] != 'aeysh,cedk,ctwipq,czzd,hsmgfqtiz,hygrekl[57 chars]lxue' : Should be aeysh,cedk,ctwipq,czzd,hsmgfqtiz,hygrekl,ijtpyblxe,mwio,npful,ootrxn,rwge,txqkeems,xlsfy,xwvto,zilxue\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['dzwzsdjs', 'hoaihqxlqi', 'oqswhrmhx', 'wbcizikbn', 'wefhey', 'xtksjzv'] != 'dshhszm,dzwzsdjs,hoaihqxlqi,oqswhrmhx,wbcizikbn,wefhey,xtksjzv' : Should be dshhszm,dzwzsdjs,hoaihqxlqi,oqswhrmhx,wbcizikbn,wefhey,xtksjzv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['cdgki', 'kwcoz', 'liqklbyq', 'lkobi', 'mhfkhokc', 'rqoz'] != 'cdgki,fdihktmg,kwcoz,liqklbyq,lkobi,mhfkhokc,rqoz' : Should be cdgki,fdihktmg,kwcoz,liqklbyq,lkobi,mhfkhokc,rqoz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['enjji', 'jolbn', 'kblfuvuut', 'owxudjcmmf', 'tymox', 'wlje'] != 'enjji,jolbn,kblfuvuut,mvmzxuif,owxudjcmmf,tymox,wlje' : Should be enjji,jolbn,kblfuvuut,mvmzxuif,owxudjcmmf,tymox,wlje\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['ajtkinundo', 'bjvq', 'dner', 'edtnijx',[201 chars]aks'] != 'ajtkinundo,bjvq,dner,edtnijx,hzxvfjz,kgp[139 chars]saks' : Should be ajtkinundo,bjvq,dner,edtnijx,hzxvfjz,kgpvyaxtcd,kgqnu,knmzpe,mjce,niky,nokkgf,ntuzuxg,nxea,objnar,opodyt,plcv,qmkhg,qvspfunec,rlgir,rrlkmxsg,rstge,szkfsxcev,vaiapreb,yujpkttle,ztnsaks\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['adaius', 'axhodxsg', 'hbgxf', 'hskjab',[75 chars]ane'] != 'adaius,axhodxsg,hbgxf,hskjab,hxfywjtg,ku[54 chars]gane' : Should be adaius,axhodxsg,hbgxf,hskjab,hxfywjtg,kurneca,ovgwff,pfkpplifqp,qzjwbk,rvxgcyajgk,tqwjd,zkhbexgane\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['airijaos', 'byvgl', 'cwjsqlnc', 'mbbwp', 'wwbkirmep'] != 'airijaos,byvgl,cwjsqlnc,mbbwp,wwbkirmep,xiqwyopj' : Should be airijaos,byvgl,cwjsqlnc,mbbwp,wwbkirmep,xiqwyopj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['axdqzulx', 'eynbapqf', 'izzuqho', 'jvsw[66 chars]vvz'] != 'axdqzulx,eynbapqf,izzuqho,jvsw,kibanwwl,[43 chars]evvz' : Should be axdqzulx,eynbapqf,izzuqho,jvsw,kibanwwl,kpmsc,missbn,nnold,otbqf,senfq,sstqhxw,tcpmevvz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['jizdidtrh', 'jrvnmxom', 'kecxsghpa', 'n[43 chars]xlc'] != 'jizdidtrh,jrvnmxom,kecxsghpa,lrmkhyib,ng[29 chars]txlc' : Should be jizdidtrh,jrvnmxom,kecxsghpa,lrmkhyib,ngys,qlnkoi,thhmur,wcrwgc,yrnimtxlc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bkwevgtk', 'ccouv', 'cusj', 'ebnsakb', [144 chars]ynz'] != 'bkwevgtk,ccouv,cusj,ebnsakb,fxzfughhh,go[102 chars]aynz' : Should be bkwevgtk,ccouv,cusj,ebnsakb,fxzfughhh,govtqmlrb,jortnsrwhh,lfaj,lzamczopp,mybztbkwvd,omqsxhean,qvjfm,rjnay,tdjycz,tels,wclverv,wxkibwbdq,xocdcaynz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['acden', 'ldlpu', 'nljln', 'pngy', 'qffuso', 'xawkzscmb'] != 'acden,gbcgu,ldlpu,nljln,pngy,qffuso,xawkzscmb' : Should be acden,gbcgu,ldlpu,nljln,pngy,qffuso,xawkzscmb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['awveolzqut', 'fzxjuicy', 'hldso', 'hoxb[157 chars]wnv'] != 'awveolzqut,fzxjuicy,hldso,hoxbfl,huczujg[112 chars]ywnv' : Should be awveolzqut,fzxjuicy,hldso,hoxbfl,huczujgck,jgethdfqe,kdroufom,knlcohi,ksyiiyx,myvfqnif,pnwpgtuvn,qinnrvvrhd,qmzxyvkhm,tssx,vxhadpyksp,vzqdz,zvvsqkfymy,zywnv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['aensi', 'bcgw', 'dqie', 'eclhlinc', 'em[209 chars]twl'] != 'aensi,bcgw,dqie,eclhlinc,emjcryo,fbnomed[151 chars]atwl' : Should be aensi,bcgw,dqie,eclhlinc,emjcryo,fbnomedqo,fmjkrdh,gvfqaryo,hhjdgndyn,hpgjwrlnc,jpcbvipqck,jxjtby,lkzm,mjpeutbrji,mkihp,nmeoued,qgxqlqgdw,sqdgmzus,uirvbeec,uqymdoyq,uvuva,vwunsd,vzdplda,yekiaatwl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['aciphual', 'dmznwfcnt', 'elosxwo', 'fsf[108 chars]rtf'] != 'aciphual,dmznwfcnt,dwii,elosxwo,fsfjw,fs[75 chars]vrtf' : Should be aciphual,dmznwfcnt,dwii,elosxwo,fsfjw,fspptgnkx,gthbae,innjocjfv,kxnxwjjffu,nqvyxjlp,ojmo,rhbkhzfc,uiyxbtshqp,ummqdvrtf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['akribzgzry', 'crkreyrtkw', 'lsyudri', '[105 chars]qbf'] != 'akribzgzry,crkreyrtkw,lsyudri,lupfqjjy,l[70 chars]qqbf' : Should be akribzgzry,crkreyrtkw,lsyudri,lupfqjjy,lymikdhe,mfgmzjl,pyidgn,qtkfb,qzgsy,uyrsbbc,vkxoiws,wapd,xleex,ysoe,zfgqqbf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['fsxbthgdp', 'qfchskmoaf', 'rugyoe'] != 'fsxbthgdp,jjlt,qfchskmoaf,rugyoe' : Should be fsxbthgdp,jjlt,qfchskmoaf,rugyoe\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['awbjqj', 'bwwvczbg', 'edow', 'fjvhv', '[151 chars]smr'] != 'awbjqj,bwwvczbg,edow,fjvhv,hujpuickp,jjq[105 chars]zsmr' : Should be awbjqj,bwwvczbg,edow,fjvhv,hujpuickp,jjqcsk,kqqn,lagor,lprgp,lrtzgqiru,matgsjz,nxnhz,ofjjm,pqiymejpz,rbinvcvvye,vzert,wrlibe,xgvyfxrekv,xzhpll,zhzsmr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['aaaq', 'cjyhpkov', 'fixg', 'gfjhd', 'ie[66 chars]yvt'] != 'aaaq,cjyhpkov,fixg,gfjhd,idsxeyzdgo,iegr[45 chars]zyvt' : Should be aaaq,cjyhpkov,fixg,gfjhd,idsxeyzdgo,iegrwv,jnvjnawb,lqkjjht,sctetbi,syhqgdzihu,tfukq,zyvt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['chsvrybwr', 'csnghtvm', 'fzxuw', 'iuoef[86 chars]jro'] != 'chsvrybwr,csnghtvm,drlhiltxmq,fzxuw,iuoe[62 chars]mjro' : Should be chsvrybwr,csnghtvm,drlhiltxmq,fzxuw,iuoef,lhvbth,ltetyfmxb,qkhab,vjweaocej,vsviurfxq,wcjj,xraogvnoka,zmjro\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['biqcibx', 'ctcy', 'dgfrcjy', 'dohhjnwzk[80 chars]dvb'] != 'biqcibx,ctcy,dgfrcjy,dohhjnwzk,gciz,ivsm[55 chars]vdvb' : Should be biqcibx,ctcy,dgfrcjy,dohhjnwzk,gciz,ivsmjgx,joovu,jrseuqvfjk,shfraxa,suvp,vbhpgrpes,vdgvejriii,vdvb\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['afpjwgu', 'ckew', 'iyaa', 'lvufmm', 'oz[48 chars]fvy'] != 'afpjwgu,bkhjipwhis,ckew,iyaa,lvufmm,ozyu[33 chars]nfvy' : Should be afpjwgu,bkhjipwhis,ckew,iyaa,lvufmm,ozyufzl,pgdukimaq,uckdkk,vrotvrxanu,ynfvy\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['eqhbcbsx', 'ftpuonwqe', 'hsbmwts', 'lsx[74 chars]bpp'] != 'eqhbcbsx,ftpuonwqe,hsbmwts,lsxdbxoei,mpd[51 chars]ppdm' : Should be eqhbcbsx,ftpuonwqe,hsbmwts,lsxdbxoei,mpdnfawp,mprp,nhudin,reepq,tbbp,tqngkfhq,vnqitbpp,vxhqppdm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['apagf', 'bcqzra', 'emqf', 'fzioteelt', [167 chars]agb'] != 'apagf,bcqzra,emqf,fzioteelt,hcqyunwf,jdm[117 chars]gvxr' : Should be apagf,bcqzra,emqf,fzioteelt,hcqyunwf,jdmjiyq,juxb,lpvji,rmjwjgcfr,roop,rotr,sgtcmtax,swmbitj,uarsasszdd,whttvd,wnfm,wxyjtkqc,xdmjrzvzxv,ysaty,yshsvplagb,zvqqgvxr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['akzawaze', 'drtxg', 'ffnelejjq', 'iaugz[58 chars]gfy'] != 'akzawaze,drtxg,ffnelejjq,iaugz,jnxecjk,k[38 chars]cgfy' : Should be akzawaze,drtxg,ffnelejjq,iaugz,jnxecjk,kfzdx,lzazoerq,plgvs,qvvcxut,tvqpenxo,zcgfy\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['abklmdpaoh', 'dctpl', 'draaw', 'fiitncr[92 chars]fbe'] != 'abklmdpaoh,dctpl,draaw,fiitncrylo,fwwrgg[68 chars]nfbe' : Should be abklmdpaoh,dctpl,draaw,fiitncrylo,fwwrggcwed,inas,jufmzl,ofvctgqxqu,onexgsgxqh,sdxychfpxq,szjlz,vuhzftrlx,xcnfbe\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['dhxegk', 'jqmvs', 'kysbjqixwe', 'pknktyq', 'rqzcn', 'zeaerquqm'] != 'dhxegk,jqmvs,kysbjqixwe,pknktyq,qbxyslm,rqzcn,zeaerquqm' : Should be dhxegk,jqmvs,kysbjqixwe,pknktyq,qbxyslm,rqzcn,zeaerquqm\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['amrlk', 'chvxrf', 'geah', 'jjjiyzju', '[38 chars]iig'] != 'amrlk,chvxrf,geah,hjkcn,jjjiyzju,jlniywz[21 chars]jiig' : Should be amrlk,chvxrf,geah,hjkcn,jjjiyzju,jlniywzcy,lshdpanyyj,srwuy,tjiig\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bysojyb', 'cahwns', 'ceobrlmx', 'ehsdp'[177 chars]cus'] != 'bysojyb,cahwns,ceobrlmx,ehsdp,ffcdyjszu,[127 chars]zcus' : Should be bysojyb,cahwns,ceobrlmx,ehsdp,ffcdyjszu,heuslwijk,hjadnp,kwopix,ooayuboerv,pmcae,pptrcm,rjcdjnfy,siwahqrho,spxtg,ssepibtq,tpasfezs,vdelnvk,vsoam,wskjxeql,wzaivc,zqpmgzzcus\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['cdewr', 'guwvequs', 'lvixeu', 'mjblnrg'[36 chars]zgf'] != 'cdewr,guwvequs,iafbugcfa,lvixeu,mjblnrg,[23 chars]qzgf' : Should be cdewr,guwvequs,iafbugcfa,lvixeu,mjblnrg,ostc,sbfn,venich,wkuxsuqzgf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['axki', 'eqxv', 'iscsvky', 'iuzww', 'jkx[173 chars]jbv'] != 'axki,azjdmg,eqxv,iscsvky,iuzww,jkxhmx,lg[118 chars]sjbv' : Should be axki,azjdmg,eqxv,iscsvky,iuzww,jkxhmx,lgqnt,mvsaj,ndslem,ngchlkn,nmmbcj,oocii,oxpupgd,pvslaxsjy,tpqqisrvvp,tubqjz,ubvoxcyvwr,ugpkye,wada,wcpgwn,yiogdtk,zbmzhzsjbv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bvinfdllk', 'ejasm', 'hbnjbsyo', 'jxbrn[74 chars]nrq'] != 'bvinfdllk,ejasm,hbnjbsyo,ietwgpvyhu,jxbr[53 chars]enrq' : Should be bvinfdllk,ejasm,hbnjbsyo,ietwgpvyhu,jxbrn,lzlxlft,pndmsftsv,ptwwze,rzwifsb,vbskcjx,yydn,zrwwnenrq\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['dgpbznugy', 'djtkscvlb', 'ibbrfhd', 'renw', 'swrol', 'zxqi'] != 'dgpbznugy,djtkscvlb,ibbrfhd,renw,swrol,zghiqdixoo,zxqi' : Should be dgpbznugy,djtkscvlb,ibbrfhd,renw,swrol,zghiqdixoo,zxqi\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bbcx', 'bgvkhgyj', 'bwgsqmbsfe', 'dynfe[212 chars]sej'] != 'bbcx,bgvkhgyj,bwgsqmbsfe,dynfecwyo,heqwc[151 chars]zsej' : Should be bbcx,bgvkhgyj,bwgsqmbsfe,dynfecwyo,heqwckf,imdicvjql,kiacie,lkxwufqoj,lsid,mooncdy,nhsd,nnhmhxik,olgcxp,omsygmnzoo,ophciewep,poei,qojuihzz,rghdlthwuv,tuotuyuvf,upgplnv,vpiedpwc,vwrn,xeiejzib,zsej\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bbshksjskx', 'fezhen', 'hzkkgjg', 'ikyj[179 chars]haz'] != 'bbshksjskx,fezhen,hzkkgjg,ikyjao,ivdpuym[126 chars]ihaz' : Should be bbshksjskx,fezhen,hzkkgjg,ikyjao,ivdpuymzhi,ixjfli,jahcdp,jkiuwr,kuyqt,miwejjczle,mnoasuf,nqjofs,oovxfrb,qittblpps,rcodo,selumzqjf,tmhlokiy,vxusli,vydiv,wflnslwtwe,ysihaz\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['ajrvnrl', 'ewpkejbeow', 'geguims', 'kxi[100 chars]uuu'] != 'ajrvnrl,ewpkejbeow,geguims,kxijxxvbu,lvl[67 chars]luuu' : Should be ajrvnrl,ewpkejbeow,geguims,kxijxxvbu,lvlbcivf,oncc,pvtx,qeofc,rckfevf,uxeqdqr,uzvujdzbid,wiyxl,xdkmjrcrgf,xluuu\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['ajhe', 'ccrjfg', 'dktu', 'famw', 'gsdka[208 chars]ftf'] != 'ajhe,ccrjfg,dktu,famw,gsdkaddhl,hawlw,hj[144 chars]mftf' : Should be ajhe,ccrjfg,dktu,famw,gsdkaddhl,hawlw,hjglg,idipolij,jwvy,lbvh,lgftexk,lxnoktlk,mdfubc,obkvqt,okislwle,olrkzqk,ppdxrmhyko,psbat,seayoymmqj,tdtvqpz,wetklgf,wfajrrx,xzwunzssb,ybfqqkd,yeomftf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['ayjlbh', 'behdfuybud', 'ecuteuipd', 'eg[61 chars]nlk'] != 'ayjlbh,behdfuybud,ecuteuipd,egekju,hfxau[37 chars]qnlk' : Should be ayjlbh,behdfuybud,ecuteuipd,egekju,hfxauc,hjldupcj,jleqkd,oqcs,prwt,pusfjak,qqnlk\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bcsu', 'cewj', 'difjmrmlnm', 'gtrk', 'g[87 chars]oyf'] != 'bcsu,cewj,difjmrmlnm,gtrk,gvxneyfyxq,ihm[56 chars]zoyf' : Should be bcsu,cewj,difjmrmlnm,gtrk,gvxneyfyxq,ihmdj,joqjd,lgsmcga,mggplea,ulkt,uqyliezcr,uuypjv,zhqtxeqc,zoyf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['drzcrqzak', 'hshrt', 'jdqbcwffpk', 'jitp', 'oimwamejt'] != 'drzcrqzak,hshrt,jdqbcwffpk,jfraqjroub,jitp,oimwamejt' : Should be drzcrqzak,hshrt,jdqbcwffpk,jfraqjroub,jitp,oimwamejt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['dvrbaef', 'gkyzvy', 'hjmu', 'kbgwuep', [71 chars]fmq'] != 'dvrbaef,ewckmgyg,gkyzvy,hjmu,kbgwuep,kwb[48 chars]jfmq' : Should be dvrbaef,ewckmgyg,gkyzvy,hjmu,kbgwuep,kwbmg,lcvfwerd,lzfrtbw,obegdrmfby,qkzsd,spoooanxe,yjfmq\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['apcrmb', 'csrx', 'drpu', 'hjoefstsm', '[42 chars]qej'] != 'apcrmb,csrx,drpu,hjoefstsm,lzbyjyfxx,mbm[26 chars]zqej' : Should be apcrmb,csrx,drpu,hjoefstsm,lzbyjyfxx,mbmwry,pzmf,rccvwyh,wvvbugxn,zqej\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['argaftowp', 'eigaqps', 'hdagmqztlm', 'h[79 chars]waf'] != 'argaftowp,eigaqps,hdagmqztlm,hupuf,nibdo[55 chars]wwaf' : Should be argaftowp,eigaqps,hdagmqztlm,hupuf,nibdob,njldpukyyt,qvrlmntns,qzhp,rbnagx,tezwdfn,tsqv,vuqres,wwaf\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['dfkgen', 'fioei', 'haltk', 'hgjzea', 'i[223 chars]twj'] != 'akzeithk,dfkgen,fioei,haltk,hgjzea,itlei[161 chars]ztwj' : Should be akzeithk,dfkgen,fioei,haltk,hgjzea,itleiu,libnqlajij,mplqseieil,mprmz,nhiu,odduum,pcpwhuuyp,pjacouh,qiozneobtq,qkdidbctqb,ruwugvemji,tpdhinwe,tpxvigqob,ubthjb,vlscdnyeb,whxc,xpcnq,ykldrxcdre,zqwtmuioo,ztwj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['alxkrnem', 'azllhciwuu', 'cuxfxr', 'dwh[190 chars]wku'] != 'alxkrnem,azllhciwuu,cuxfxr,dwhjpwb,eactl[137 chars]swku' : Should be alxkrnem,azllhciwuu,cuxfxr,dwhjpwb,eactluoth,habpdcb,ialcmter,ilfzvur,iqtdj,jvvxf,leszuyfq,oooeetji,pdjywehnxj,qbjxbk,sjerxiz,trcsbgbrqp,vaixhf,xhuczzunqc,xnwovslqw,zdejg,zmubhnswku\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['awzpsiojab', 'aywwy', 'biph', 'disgqr',[216 chars]wsl'] != 'awzpsiojab,aywwy,biph,disgqr,dzckkizvw,d[156 chars]owsl' : Should be awzpsiojab,aywwy,biph,disgqr,dzckkizvw,dzxl,ffwrbkkccy,grhrecor,kkqq,knwi,krxra,lurbxa,mnryochaj,ojylwy,pbbnqibbb,pnwuvsifq,rcwmdqbadt,roqxbosida,ruvayosie,sxojyxjijy,toveloi,uokvzr,xzlvovq,yzox,zowsl\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['auhhfan', 'bznhyvhyy', 'fkqm', 'ivbjafv[77 chars]pkj'] != 'auhhfan,bznhyvhyy,fkqm,ivbjafvvt,lipqzel[52 chars]ppkj' : Should be auhhfan,bznhyvhyy,fkqm,ivbjafvvt,lipqzelxga,nvez,oyuf,ptpf,qiagxujpc,sipfxbr,uiph,yycsts,zpvppkj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['abrhfdqih', 'bbdkyejbuh', 'byyjfjkco', [233 chars]uoh'] != 'abrhfdqih,bbdkyejbuh,byyjfjkco,cpspdtdec[173 chars]zuoh' : Should be abrhfdqih,bbdkyejbuh,byyjfjkco,cpspdtdec,cqsmvjrrwk,fnfhrtoem,grclc,izftxshg,kcttmqc,knsyvhsaj,kszxomqkbk,owtickvq,qghvsn,qlwlpjhldr,qukcsgetr,slyvj,sptammsc,tcskvmpsi,twlykkza,vixbv,vxzztsilwi,wftz,wrfdxf,xbttny,zuoh\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['baojaul', 'bfha', 'cxhy', 'erfkqqzv', '[143 chars]lwp'] != 'baojaul,bfha,cxhy,erfkqqzv,howtipzhb,jdc[96 chars]flwp' : Should be baojaul,bfha,cxhy,erfkqqzv,howtipzhb,jdcugte,libi,lknph,mqbn,naqqqkbfuo,nsemtc,obrs,pldyabfdzb,pnglhywk,reomntp,uolmd,wofcx,yuhkhdtqun,zflwp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bgptsjdpqj', 'domawajs', 'jnwd', 'ldxa'[99 chars]cdp'] != 'azfvq,bgptsjdpqj,domawajs,jnwd,ldxa,lqcn[64 chars]pcdp' : Should be azfvq,bgptsjdpqj,domawajs,jnwd,ldxa,lqcnknv,nnjwfly,rnjtkuua,svcp,uniimjke,vdsomff,wnmjfh,xkzxkyw,xvlk,ypcdp\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['allwgc', 'cjmchiwrzh', 'diryfcjn', 'esw[130 chars]ewr'] != 'allwgc,cjmchiwrzh,diryfcjn,eswanemln,exa[91 chars]xewr' : Should be allwgc,cjmchiwrzh,diryfcjn,eswanemln,exacczx,ijjxmk,jdizuisp,njmeygtbok,odjdnys,ohhkhdufl,pkixlbfbhc,rxprqsy,tjyozyju,ufaq,xntcwb,yxewr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['awelk', 'daecmcskcf', 'eyyd', 'jrfljs',[108 chars]nip'] != 'awelk,bxmgoij,daecmcskcf,eyyd,jrfljs,lce[75 chars]jnip' : Should be awelk,bxmgoij,daecmcskcf,eyyd,jrfljs,lcetml,lcwwld,lutnw,myzilkz,nmsifrxg,nxvtkuspn,qalshgb,qlykqrlrap,uzkcm,ycxlphjnip\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['aafup', 'amkrfgww', 'axsz', 'bycxnv', '[191 chars]lvt'] != 'aafup,amkrfgww,axsz,bycxnv,fnhqv,gkepyaj[135 chars]ylvt' : Should be aafup,amkrfgww,axsz,bycxnv,fnhqv,gkepyajw,hyevhpxd,lpjmwsi,nrnarz,oaxmizyq,ppnas,sozielmtf,szov,tiprf,ufrugxp,vjnamvyr,vlygdix,vnftbrlo,wlzh,wmrrdyly,xzisujlxmr,ycoptey,zqbtiaylvt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bbexzevste', 'emzpkee', 'heccwvyazw', '[71 chars]hqv'] != 'bbexzevste,emzpkee,heccwvyazw,mewnx,mpbg[52 chars]phqv' : Should be bbexzevste,emzpkee,heccwvyazw,mewnx,mpbgmb,ngmkzao,osfy,qvdghbjgwo,sokmaanplh,tzkfvfwwm,ycmsphqv\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['hkmjszeqre', 'owfmrfsxmk', 'qnrnrqyo', 'qszhu', 'uzqrotvhmt'] != 'hkmjszeqre,owfmrfsxmk,qnrnrqyo,qszhu,uxlqist,uzqrotvhmt' : Should be hkmjszeqre,owfmrfsxmk,qnrnrqyo,qszhu,uxlqist,uzqrotvhmt\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['bhpjnwdnu', 'bhsrfa', 'fudhpxf', 'gohzq[119 chars]csc'] != 'bhpjnwdnu,bhsrfa,fudhpxf,gohzqjziz,ioaeb[81 chars]tcsc' : Should be bhpjnwdnu,bhsrfa,fudhpxf,gohzqjziz,ioaebe,jyecydhj,kaeuso,krct,nbnrlq,nkhzvfahu,prmo,pykc,qjjwq,sial,wqfulvnhq,znfoy,zrtctcsc\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['ifffepjbjh', 'knuivdnhjo', 'ngrxfdvfgx', 'sqlxzjrioc', 'tbhkkkgkj'] != 'ifffepjbjh,knuivdnhjo,ngrxfdvfgx,qzunch,sqlxzjrioc,tbhkkkgkj' : Should be ifffepjbjh,knuivdnhjo,ngrxfdvfgx,qzunch,sqlxzjrioc,tbhkkkgkj\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['agkkxy', 'araqweqa', 'bklxb', 'cwqkpqv'[229 chars]nlr'] != 'agkkxy,araqweqa,bklxb,cwqkpqv,egxbztj,ff[168 chars]snlr' : Should be agkkxy,araqweqa,bklxb,cwqkpqv,egxbztj,ffqqxcbus,hhkahigbba,hwmki,jinkjkva,khprhekhhz,mhlkyodlu,nhiybw,ombbpam,pdcjfcqb,qaliwankfa,qsdujfzvmo,qwqrpvjjp,rwbyhumlxl,rxnudxxvll,vfanbxfnhh,vovphrnii,ybtnpw,zbkq,zksnlr\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['ehbbnwl', 'hnyzqncrw', 'inyybqkqb', 'jr[181 chars]igs'] != 'ehbbnwl,hnyzqncrw,inyybqkqb,jrequuvobn,j[132 chars]ligs' : Should be ehbbnwl,hnyzqncrw,inyybqkqb,jrequuvobn,jwdqeumwev,jzidgmofu,kgitdlqqz,kmyeugvwq,lcjktezwwv,ldqj,maebgqdyr,msofac,oynuekq,pfgz,pkyeoz,pnlkvqmcjg,tovgpewjdz,upxq,vbww,veowr,zligs\n",
      "\n",
      "======================================================================\n",
      "FAIL: runTest (mod.testing.test_alpha.<locals>.TestKnown)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"/root/jupyter/lab-functions-es/mod/testing.py\", line 187, in runTest\n",
      "    self.assertEqual(fn(self.input), self.output, f\"Should be {self.output}\")\n",
      "AssertionError: ['apegodyl', 'aprkespt', 'cbgkg', 'dlpoii[114 chars]wrg'] != 'apegodyl,aprkespt,cbgkg,dlpoii,fdpm,khqw[81 chars]fvfk' : Should be apegodyl,aprkespt,cbgkg,dlpoii,fdpm,khqwmzz,mlvuyssn,ogiqpko,pgitajnaf,phdenfeii,pqtkvi,psdgs,rrlcrv,txoign,velwrg,ylchggfvfk\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.339s\n",
      "\n",
      "FAILED (failures=100)\n"
     ]
    }
   ],
   "source": [
    "# Para testear tu función \n",
    "test_alpha(sort_alpha)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Escribe una función para verificar si una contraseña dada es fuerte (al menos 8 caracteres, al menos una minúscula, al menos una mayúscula, al menos un número y al menos un carácter especial). Debería devolver True si es fuerte y False si no lo es."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def check_pass(password):\n",
    "#tu codigo aquí"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Para testear tu función\n",
    "test_pass(check_pass)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  },
  "vscode": {
   "interpreter": {
    "hash": "aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
